[package]
name = "sc2pathlib"
version = "0.3.1"
edition = "2018"

[lib]
name = "sc2pathlib"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]

[dependencies]
pathfinding = "2.0.4"

# [profile.release]
# opt-level = 3
# debug=false
# panic="abort"
# lto = "fat"
# codegen-units = 1
