[package]
name = "sc2pathlib"
version = "0.3.1"
edition = "2018"

[lib]
name = "sc2pathlib"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.11.0"
features = ["extension-module"]

[dependencies]
pathfinding = "2.0.4"

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "path_benchmark"
harness = false
# [profile.release]
# opt-level = 3
# debug=false
# panic="abort"
# lto = "fat"
# codegen-units = 1
